apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      # Relative path to the chart dir
      chart: ./assets/charts/components/external-dns/
      sourceRef:
        kind: GitRepository
        name: lokomotive
      # If a third party updates the version then we will have an automatic update mechanism in place.
      version: 5.1.1
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 10m0s
  # Namespace of the external-dns component.
  targetNamespace: external-dns
  # Chart's values file.
  valuesFrom:
  - kind: Secret
    name: external-dns-values
    valuesKey: values
