apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: httpbin
  namespace: flux-system
spec:
  chart:
    spec:
      # Relative path to the chart dir
      chart: ./assets/charts/components/httpbin/
      sourceRef:
        kind: GitRepository
        name: lokomotive
      # If a third party updates the version then we will have an automatic update mechanism in place.
      version: 0.1.0
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 10m0s
  # Namespace of the httpbin component.
  targetNamespace: httpbin
  # Chart's values file.
  values:
    certManagerClusterIssuer: letsencrypt-production
    ingressHost: surajhttpbin.dev.lokomotive-k8s.net
