apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      # Relative path to the chart dir
      chart: ./assets/charts/components/metallb/
      sourceRef:
        kind: GitRepository
        name: lokomotive
      # If a third party updates the version then we will have an automatic update mechanism in place.
      version: 0.1.0
  install:
    crds: CreateReplace
    # Contour ships the namespace config.
    createNamespace: false
  interval: 10m0s
  # Namespace of the metallb component.
  targetNamespace: metallb-system
  # Chart's values file.
  values:
    addressPools:
      default:
      - 147.75.68.76/32
