apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-operator
  namespace: flux-system
spec:
  chart:
    spec:
      # Relative path to the chart dir
      chart: ./assets/charts/components/openebs-operator/
      sourceRef:
        kind: GitRepository
        name: lokomotive
      # If a third party updates the version then we will have an automatic update mechanism in place.
      version: 2.10.3
  install:
    # Contour ships the namespace config.
    createNamespace: true
  interval: 10m0s
  # Namespace of the openebs component.
  targetNamespace: openebs
  values:
    rbac:
      pspEnabled: true
